config_dir: "/home/radicle/.config"
data_dir: "/home/radicle/.local/share"
state_dir: "/home/radicle/.local/state"
bin_dir: "/home/radicle/.local/bin"

nodejs_version: "24.x"
nodejs_npm_global_packages:
  - name: pnpm
  - name: sqlite3

### Caddy
caddy_config: "{{ lookup('template', '../templates/Caddyfile.gardener.j2') }}"
# allow caddy to open ports under 1024 (e.g. 80 / 443)
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_user: radicle

### Security
system_username: radicle
system_group: radicle
security_sudoers_passwordless:
  - radicle
security_autoupdate_enabled: true
security_autoupdate_reboot: false

firewall_state: started
firewall_enabled_at_boot: true
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "5173"
  - "8776"
  - "7000:8000"
