nodejs_version: "24.x"
nodejs_npm_global_packages:
  - name: pnpm

### Caddy
# allow caddy to open ports under 1024 (e.g. 80 / 443)
caddy_setcap: true
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_packages: ["github.com/caddy-dns/cloudflare"]

unix_user_id: 1001
unix_group_id: 1001

### Security
security_autoupdate_enabled: true
security_autoupdate_reboot: false

firewall_state: started
firewall_enabled_at_boot: true
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "5173"
  - "8776"
  - "5432"
  - "7000:8000"
