config_dir: "/home/vagrant/.config"
data_dir: "/home/vagrant/.local/share"
state_dir: "/home/vagrant/.local/state"
bin_dir: "/home/vagrant/.local/bin"

caddy_user: "vagrant"

### Security
system_username: "vagrant"
system_group: "vagrant"
security_sudoers_passwordless:
  - vagrant
security_autoupdate_enabled: true
security_autoupdate_reboot: false

### Postgres
postgres_user: garden
postgres_password: garden
postgres_db: garden
postgres_port: 5432
postgres_data_dir: "{{ data_dir }}/postgres"
