name: Build and Push radicle-node Container

on:
  push:
    paths:
      - 'infra/containers/radicle-node/**'
      - '.github/workflows/build-radicle-node.yml'
  workflow_dispatch:
    inputs:
      alpine_version:
        description: 'Version of Alpine base image'
        required: true
        default: '3.23'

env:
  REGISTRY: quay.io
  HEARTWOOD_IMAGE_NAME: radicle_garden/heartwood
  RADICLE_NODE_IMAGE_NAME: radicle_garden/radicle-node
  ALPINE_VERSION: '3.23'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Run tests
        working-directory: infra/containers/radicle-node/heartwood
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug
          CARGO_TARGET_DIR: /tmp/target
        run: |
          cargo --version

          cargo fmt --check
          cargo clippy --all-targets --workspace -- --deny warnings
          cargo build --all-targets --workspace
          cargo doc --workspace --no-deps
          cargo test --workspace --no-fail-fast -- --test-threads=1

  extract-version:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      radicle_version: ${{ steps.extract.outputs.radicle_version }}
      source_date_epoch: ${{ steps.extract.outputs.source_date_epoch }}
      git_head: ${{ steps.extract.outputs.git_head }}
      tags: ${{ steps.extract.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Extract version information
        id: extract
        working-directory: infra/containers/radicle-node/heartwood
        run: |
          git --version

          git fetch --all 

          # Set source date. This is honored by `asciidoctor` and other tools.
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          RADICLE_VERSION=$(./build/version)
          GIT_HEAD=$(git rev-parse --short HEAD)

          echo "radicle_version=$RADICLE_VERSION" >> $GITHUB_OUTPUT
          echo "source_date_epoch=$SOURCE_DATE_EPOCH" >> $GITHUB_OUTPUT
          echo "git_head=$GIT_HEAD" >> $GITHUB_OUTPUT
          echo "tags=$RADICLE_VERSION" >> $GITHUB_OUTPUT

          echo "version: $RADICLE_VERSION, date: $SOURCE_DATE_EPOCH, git head: $GIT_HEAD"

  build-heartwood:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs: extract-version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.HEARTWOOD_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.extract-version.outputs.radicle_version }}
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            quay.expires-after=${{ github.event_name == 'pull_request' && '7d' || '' }}

      - name: Build and push heartwood image
        uses: docker/build-push-action@v6
        with:
          context: infra/containers/radicle-node/heartwood
          file: infra/containers/radicle-node/heartwood/build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LC_ALL=C
            TZ=UTC0
            RADICLE_VERSION=${{ needs.extract-version.outputs.radicle_version }}
            SOURCE_DATE_EPOCH=${{ needs.extract-version.outputs.source_date_epoch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build-radicle-node:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            value: x86_64-unknown-linux-musl
            suffix: "-amd64"
            runner: ubuntu-latest
          - platform: linux/arm64
            value: aarch64-unknown-linux-musl
            suffix: "-arm64"
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    needs: [extract-version, build-heartwood]
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ALPINE_VERSION=${{ github.event.inputs.alpine_version }}" >> $GITHUB_OUTPUT
          else
            echo "ALPINE_VERSION=${{ env.ALPINE_VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push radicle-node image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: infra/containers/radicle-node
          file: infra/containers/radicle-node/Containerfile
          tags: ${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LC_ALL=C
            TZ=UTC0
            PLATFORM=${{ matrix.value }}
            RADICLE_VERSION=${{ needs.extract-version.outputs.radicle_version }}
            ALPINE_VERSION=${{ steps.version.outputs.ALPINE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1


  merge:
    runs-on: ubuntu-latest
    needs: [extract-version, build-radicle-node]
    steps:

      - name: Download digests
        uses: actions/download-artifact@v6
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.extract-version.outputs.radicle_version }}${{ matrix.suffix }}
            type=ref,event=pr,suffix=${{ matrix.suffix }}
            type=raw,value=latest${{ matrix.suffix }},enable={{is_default_branch}}
          labels: |
            quay.expires-after=${{ github.event_name == 'pull_request' && '7d' || '' }}


      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}@sha256:%s ' *)


      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}:${{ steps.meta.outputs.version }}


      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.RADICLE_NODE_IMAGE_NAME }}:${{ steps.meta.outputs.version }}
